const labels={en:'English','zh-CN':'简体中文','zh-TW':'繁體中文',th:'ไทย',ru:'Русский'}
function detect(){const saved=localStorage.getItem('thaitype-locale');if(labels[saved])return saved;const l=(navigator.languages?.[0]||navigator.language||'en').toLowerCase();if(/^zh-(tw|hk|mo)/.test(l)||l.includes('hant'))return'zh-TW';if(l.startsWith('zh'))return'zh-CN';if(l.startsWith('th'))return'th';if(l.startsWith('ru'))return'ru';return'en'}
export const locale=detect()
export const copy={
en:{title:'ThaiType VIP | Improve Your Thai Typing Faster',nav:['Free Practice','Features','Pricing'],eye:'ThaiType VIP',h1:'Turn every practice session into measurable progress.',lead:'Full typing history, weak-key insights, progress trends, saved practice and verified certificates—completely separate from the free practice experience.',plans:'View plans',signin:'Member sign-in coming soon',features:[['Progress history','Review every session and see how your speed and accuracy change.'],['Weak-key insights','Find recurring mistakes and focus practice where it matters.'],['Verified certificates','Create professional, shareable proof of your typing results.']],early:'Early access',priceTitle:'VIP membership is being prepared.',priceText:'This project shell is ready for authentication, checkout and the member dashboard.',free:'Keep practising free',about:'About ThaiType'},
'zh-CN':{title:'ThaiType VIP | 更快提升泰语打字',nav:['免费练习','功能','价格'],eye:'ThaiType VIP',h1:'让每一次练习都成为可衡量的进步。',lead:'完整打字历史、薄弱按键分析、进度趋势、保存练习和可验证证书——与免费练习完全独立的体验。',plans:'查看方案',signin:'会员登录即将开放',features:[['进度历史','回顾每次练习，了解速度和准确率的变化。'],['薄弱按键分析','发现反复出现的错误，将练习集中在真正需要的地方。'],['可验证证书','创建专业、可分享的打字成绩证明。']],early:'早期体验',priceTitle:'VIP 会员正在准备中。',priceText:'独立项目骨架已为身份验证、支付和会员控制台做好准备。',free:'继续免费练习',about:'关于 ThaiType'},
'zh-TW':{title:'ThaiType VIP | 更快提升泰語打字',nav:['免費練習','功能','價格'],eye:'ThaiType VIP',h1:'讓每一次練習都成為可衡量的進步。',lead:'完整打字歷史、弱項按鍵分析、進度趨勢、儲存練習和可驗證證書——與免費練習完全獨立的體驗。',plans:'查看方案',signin:'會員登入即將開放',features:[['進度歷史','回顧每次練習，了解速度與準確率的變化。'],['弱項按鍵分析','找出重複錯誤，把練習集中在真正需要的地方。'],['可驗證證書','建立專業、可分享的打字成績證明。']],early:'早期體驗',priceTitle:'VIP 會員正在準備中。',priceText:'獨立專案骨架已為身分驗證、付款和會員控制台做好準備。',free:'繼續免費練習',about:'關於 ThaiType'},
th:{title:'ThaiType VIP | พัฒนาการพิมพ์ไทยให้เร็วขึ้น',nav:['ฝึกฟรี','คุณสมบัติ','ราคา'],eye:'ThaiType VIP',h1:'เปลี่ยนทุกการฝึกให้เป็นพัฒนาการที่วัดผลได้',lead:'ประวัติการพิมพ์ทั้งหมด วิเคราะห์ปุ่มที่อ่อน แนวโน้ม บันทึกแบบฝึก และใบรับรองที่ตรวจสอบได้—แยกจากประสบการณ์ฟรีอย่างสมบูรณ์',plans:'ดูแพ็กเกจ',signin:'ระบบสมาชิกกำลังจะเปิด',features:[['ประวัติพัฒนาการ','ทบทวนทุกเซสชันและดูการเปลี่ยนแปลงของความเร็วและความแม่นยำ'],['วิเคราะห์ปุ่มที่อ่อน','ค้นหาข้อผิดพลาดซ้ำและเน้นฝึกในจุดที่สำคัญ'],['ใบรับรองตรวจสอบได้','สร้างหลักฐานผลการพิมพ์ที่เป็นมืออาชีพและแชร์ได้']],early:'สิทธิ์ทดลอง',priceTitle:'กำลังเตรียมสมาชิก VIP',priceText:'โครงสร้างโครงการพร้อมสำหรับการยืนยันตัวตน การชำระเงิน และแดชบอร์ดสมาชิก',free:'ฝึกฟรีต่อ',about:'เกี่ยวกับ ThaiType'},
ru:{title:'ThaiType VIP | Улучшайте тайскую печать быстрее',nav:['Бесплатная практика','Возможности','Цены'],eye:'ThaiType VIP',h1:'Превратите каждую тренировку в измеримый прогресс.',lead:'Полная история, анализ слабых клавиш, динамика, сохранённые упражнения и проверяемые сертификаты — отдельно от бесплатного сайта.',plans:'Посмотреть планы',signin:'Вход для участников скоро появится',features:[['История прогресса','Просматривайте каждую сессию и изменения скорости и точности.'],['Анализ слабых клавиш','Находите повторяющиеся ошибки и тренируйте самое важное.'],['Проверяемые сертификаты','Создавайте профессиональное подтверждение результатов.']],early:'Ранний доступ',priceTitle:'Мы готовим VIP-подписку.',priceText:'Основа проекта готова для авторизации, оплаты и личного кабинета.',free:'Продолжить бесплатно',about:'О ThaiType'}
}[locale]
export const practiceCopy={
en:{eye:'VIP Practice Lab',title:'Advanced Thai typing practice',words:'500 common words',custom:'Unlimited custom text',voice:'Thai voice',theme:'Keyboard style',customPlaceholder:'Paste any amount of Thai text…',start:'Generate practice',speak:'Hear next word',input:'Type the text shown above…',ready:'Choose a mode and generate a new practice.',progress:'Progress',accuracy:'Accuracy',defaultVoice:'Browser default Thai voice',themes:['Emerald','Midnight','Sunset','Ocean']},
'zh-CN':{eye:'VIP 练习室',title:'高级泰语打字练习',words:'500 个常用词',custom:'不限长度自定义文本',voice:'泰语声音',theme:'键盘样式',customPlaceholder:'粘贴任意长度的泰语文本…',start:'生成练习',speak:'朗读下一个词',input:'输入上方显示的文字…',ready:'选择模式并生成新的练习。',progress:'进度',accuracy:'准确率',defaultVoice:'浏览器默认泰语声音',themes:['翡翠','深夜','日落','海洋']},
'zh-TW':{eye:'VIP 練習室',title:'進階泰語打字練習',words:'500 個常用詞',custom:'不限長度自訂文字',voice:'泰語聲音',theme:'鍵盤樣式',customPlaceholder:'貼上任意長度的泰語文字…',start:'產生練習',speak:'朗讀下一個詞',input:'輸入上方顯示的文字…',ready:'選擇模式並產生新的練習。',progress:'進度',accuracy:'準確率',defaultVoice:'瀏覽器預設泰語聲音',themes:['翡翠','深夜','日落','海洋']},
th:{eye:'ห้องฝึก VIP',title:'ฝึกพิมพ์ไทยขั้นสูง',words:'คำที่ใช้บ่อย 500 คำ',custom:'ข้อความกำหนดเองไม่จำกัด',voice:'เสียงภาษาไทย',theme:'รูปแบบแป้นพิมพ์',customPlaceholder:'วางข้อความภาษาไทยได้ไม่จำกัด…',start:'สร้างแบบฝึก',speak:'ฟังคำถัดไป',input:'พิมพ์ข้อความที่แสดงด้านบน…',ready:'เลือกโหมดแล้วสร้างแบบฝึกใหม่',progress:'ความคืบหน้า',accuracy:'ความแม่นยำ',defaultVoice:'เสียงไทยเริ่มต้นของเบราว์เซอร์',themes:['มรกต','เที่ยงคืน','พระอาทิตย์ตก','มหาสมุทร']},
ru:{eye:'VIP-лаборатория',title:'Расширенная практика тайской печати',words:'500 частотных слов',custom:'Свой текст без ограничений',voice:'Тайский голос',theme:'Стиль клавиатуры',customPlaceholder:'Вставьте тайский текст любой длины…',start:'Создать упражнение',speak:'Прослушать следующее слово',input:'Печатайте текст выше…',ready:'Выберите режим и создайте упражнение.',progress:'Прогресс',accuracy:'Точность',defaultVoice:'Стандартный тайский голос браузера',themes:['Изумруд','Полночь','Закат','Океан']}
}[locale]
Object.assign(practiceCopy,{
en:{wordCount:'Random word count',hideHints:'Keyboard hints: On',showHints:'Keyboard hints: Off',audioOn:'Voice feedback: On',audioOff:'Voice feedback: Off',imeWarning:'Thai keyboard required. Switch your system input method to Thai (Kedmanee) to continue.'},
'zh-CN':{wordCount:'随机单词数量',hideHints:'键盘提示：开',showHints:'键盘提示：关',audioOn:'语音反馈：开',audioOff:'语音反馈：关',imeWarning:'需要泰语键盘。请将系统输入法切换为泰语（Kedmanee）后继续。'},
'zh-TW':{wordCount:'隨機單字數量',hideHints:'鍵盤提示：開',showHints:'鍵盤提示：關',audioOn:'語音回饋：開',audioOff:'語音回饋：關',imeWarning:'需要泰語鍵盤。請將系統輸入法切換為泰語（Kedmanee）後繼續。'},
th:{wordCount:'จำนวนคำแบบสุ่ม',hideHints:'คำใบ้แป้นพิมพ์: เปิด',showHints:'คำใบ้แป้นพิมพ์: ปิด',audioOn:'เสียงตอบกลับ: เปิด',audioOff:'เสียงตอบกลับ: ปิด',imeWarning:'ต้องใช้แป้นพิมพ์ภาษาไทย โปรดเปลี่ยนภาษาระบบเป็นไทย (Kedmanee) เพื่อฝึกต่อ'},
ru:{wordCount:'Количество случайных слов',hideHints:'Подсказки клавиатуры: вкл.',showHints:'Подсказки клавиатуры: выкл.',audioOn:'Озвучивание: вкл.',audioOff:'Озвучивание: выкл.',imeWarning:'Требуется тайская клавиатура. Переключите системную раскладку на Thai (Kedmanee), чтобы продолжить.'}
}[locale])
const dashboard={
en:{nav:['Dashboard','Practice','History','Insights','Certificates'],settings:'Account settings',welcome:'Welcome back to your Thai typing journey.',welcomeText:'Train with purpose, understand every mistake, and keep a permanent record of your progress.',start:'Start VIP practice',best:'Personal best',bestNote:'All-time typing speed',accuracy:'Average accuracy',accuracyNote:'Across all sessions',sessions:'Total sessions',sessionsNote:'Saved permanently',streak:'Current streak',days:'days',dailyGoal:'Daily goal',sessionsLabel:'sessions',recent:'Recent sessions',trend:'Progress trend',lastSeven:'Last 7 sessions',noLimits:'VIP · No limits · No ads',historyEye:'Your training record',historyTitle:'Complete practice history',export:'Export CSV',date:'Date',mode:'Mode',duration:'Duration',insightsEye:'Mistake intelligence',insightsTitle:'Know exactly what to practise next',weakKeys:'Most missed Thai characters',recommendation:'Recommended next step',keepPractising:'Complete a practice to unlock your recommendation.',practiceWeak:'Practise weak keys',focusOn:'Focus your next practice on',certEye:'Verified achievement',certTitle:'Certificates that prove your progress',certText:'Create high-resolution, watermark-free certificates from qualifying results.',certificateName:'Thai Typing Achievement',certPlaceholder:'Your best qualifying score will appear here.',availableAfter:'Available after a qualifying session',memberWorkspace:'Personal member workspace',noSessions:'Complete your first VIP practice to see results here.',noMistakes:'No repeated mistakes yet.'},
'zh-CN':{nav:['仪表盘','练习','历史','分析','证书'],settings:'账户设置',welcome:'欢迎继续你的泰语打字旅程。',welcomeText:'有目标地训练，理解每一个错误，并永久记录你的进步。',start:'开始 VIP 练习',best:'个人最佳',bestNote:'历史最高打字速度',accuracy:'平均准确率',accuracyNote:'全部练习平均值',sessions:'练习次数',sessionsNote:'永久保存',streak:'连续练习',days:'天',dailyGoal:'每日目标',sessionsLabel:'次练习',recent:'最近练习',trend:'进步趋势',lastSeven:'最近 7 次练习',noLimits:'VIP · 不限长度 · 无广告',historyEye:'你的训练记录',historyTitle:'完整练习历史',export:'导出 CSV',date:'日期',mode:'模式',duration:'时长',insightsEye:'错误智能分析',insightsTitle:'明确下一步应该练什么',weakKeys:'最常输错的泰文字',recommendation:'下一步建议',keepPractising:'完成一次练习后生成针对性建议。',practiceWeak:'练习薄弱按键',focusOn:'下一次重点练习',certEye:'可验证的成就',certTitle:'用证书证明你的进步',certText:'根据合格成绩生成高清、无水印证书。',certificateName:'泰语打字能力证书',certPlaceholder:'符合要求的最佳成绩将显示在这里。',availableAfter:'完成合格练习后可用',memberWorkspace:'个人会员工作台',noSessions:'完成第一次 VIP 练习后，这里会显示成绩。',noMistakes:'目前没有重复错误。'},
'zh-TW':{nav:['儀表板','練習','歷史','分析','證書'],settings:'帳戶設定',welcome:'歡迎繼續你的泰語打字旅程。',welcomeText:'有目標地訓練，理解每一個錯誤，並永久記錄你的進步。',start:'開始 VIP 練習',best:'個人最佳',bestNote:'歷史最高打字速度',accuracy:'平均準確率',accuracyNote:'全部練習平均值',sessions:'練習次數',sessionsNote:'永久儲存',streak:'連續練習',days:'天',dailyGoal:'每日目標',sessionsLabel:'次練習',recent:'最近練習',trend:'進步趨勢',lastSeven:'最近 7 次練習',noLimits:'VIP · 不限長度 · 無廣告',historyEye:'你的訓練記錄',historyTitle:'完整練習歷史',export:'匯出 CSV',date:'日期',mode:'模式',duration:'時間',insightsEye:'錯誤智慧分析',insightsTitle:'清楚知道下一步該練什麼',weakKeys:'最常輸錯的泰文字',recommendation:'下一步建議',keepPractising:'完成一次練習後產生針對性建議。',practiceWeak:'練習弱項按鍵',focusOn:'下一次重點練習',certEye:'可驗證的成就',certTitle:'用證書證明你的進步',certText:'根據合格成績產生高清、無浮水印證書。',certificateName:'泰語打字能力證書',certPlaceholder:'符合要求的最佳成績將顯示在這裡。',availableAfter:'完成合格練習後可用',memberWorkspace:'個人會員工作區',noSessions:'完成第一次 VIP 練習後，這裡會顯示成績。',noMistakes:'目前沒有重複錯誤。'},
th:{nav:['แดชบอร์ด','ฝึกพิมพ์','ประวัติ','การวิเคราะห์','ใบรับรอง'],settings:'ตั้งค่าบัญชี',welcome:'ยินดีต้อนรับกลับสู่เส้นทางการพิมพ์ไทย',welcomeText:'ฝึกอย่างมีเป้าหมาย เข้าใจทุกข้อผิดพลาด และเก็บประวัติพัฒนาการไว้อย่างถาวร',start:'เริ่มฝึก VIP',best:'สถิติส่วนตัว',bestNote:'ความเร็วสูงสุดตลอดกาล',accuracy:'ความแม่นยำเฉลี่ย',accuracyNote:'เฉลี่ยจากทุกเซสชัน',sessions:'จำนวนเซสชัน',sessionsNote:'บันทึกถาวร',streak:'ฝึกต่อเนื่อง',days:'วัน',dailyGoal:'เป้าหมายรายวัน',sessionsLabel:'เซสชัน',recent:'เซสชันล่าสุด',trend:'แนวโน้มพัฒนาการ',lastSeven:'7 เซสชันล่าสุด',noLimits:'VIP · ไม่จำกัด · ไม่มีโฆษณา',historyEye:'บันทึกการฝึก',historyTitle:'ประวัติการฝึกทั้งหมด',export:'ส่งออก CSV',date:'วันที่',mode:'โหมด',duration:'ระยะเวลา',insightsEye:'วิเคราะห์ข้อผิดพลาด',insightsTitle:'รู้ว่าควรฝึกอะไรต่อไป',weakKeys:'อักษรไทยที่พิมพ์ผิดบ่อย',recommendation:'คำแนะนำถัดไป',keepPractising:'ทำแบบฝึกเพื่อรับคำแนะนำเฉพาะบุคคล',practiceWeak:'ฝึกปุ่มที่อ่อน',focusOn:'แบบฝึกถัดไปเน้น',certEye:'ความสำเร็จที่ตรวจสอบได้',certTitle:'ใบรับรองที่พิสูจน์พัฒนาการ',certText:'สร้างใบรับรองความละเอียดสูง ไม่มีลายน้ำจากผลที่ผ่านเกณฑ์',certificateName:'ใบรับรองทักษะการพิมพ์ไทย',certPlaceholder:'คะแนนที่ผ่านเกณฑ์ดีที่สุดจะแสดงที่นี่',availableAfter:'ใช้ได้หลังจบเซสชันที่ผ่านเกณฑ์',memberWorkspace:'พื้นที่สมาชิกส่วนบุคคล',noSessions:'ทำแบบฝึก VIP ครั้งแรกเพื่อดูผลลัพธ์ที่นี่',noMistakes:'ยังไม่มีข้อผิดพลาดซ้ำ'},
ru:{nav:['Панель','Практика','История','Анализ','Сертификаты'],settings:'Настройки аккаунта',welcome:'Продолжайте свой путь в тайской печати.',welcomeText:'Тренируйтесь осознанно, разбирайте ошибки и сохраняйте прогресс навсегда.',start:'Начать VIP-практику',best:'Личный рекорд',bestNote:'Максимальная скорость',accuracy:'Средняя точность',accuracyNote:'По всем сессиям',sessions:'Всего сессий',sessionsNote:'Сохранены навсегда',streak:'Серия занятий',days:'дней',dailyGoal:'Цель на день',sessionsLabel:'сессий',recent:'Последние сессии',trend:'Динамика прогресса',lastSeven:'Последние 7 сессий',noLimits:'VIP · Без ограничений · Без рекламы',historyEye:'Ваши тренировки',historyTitle:'Полная история практики',export:'Экспорт CSV',date:'Дата',mode:'Режим',duration:'Длительность',insightsEye:'Анализ ошибок',insightsTitle:'Точно знайте, что тренировать дальше',weakKeys:'Частые ошибки в тайских символах',recommendation:'Следующий шаг',keepPractising:'Завершите практику для персональной рекомендации.',practiceWeak:'Тренировать слабые клавиши',focusOn:'В следующей практике уделите внимание',certEye:'Проверяемое достижение',certTitle:'Сертификаты вашего прогресса',certText:'Создавайте сертификаты высокого разрешения без водяных знаков.',certificateName:'Достижение в тайской печати',certPlaceholder:'Здесь появится лучший подходящий результат.',availableAfter:'Доступно после подходящей сессии',memberWorkspace:'Личный кабинет участника',noSessions:'Завершите первую VIP-практику, чтобы увидеть результаты.',noMistakes:'Повторяющихся ошибок пока нет.'}
}
export const dashboardCopy=dashboard[locale]
const coaching={
en:{reportEye:'VIP adaptive coach',reportTitle:'Your practice diagnosis',why:'Why mistakes happened',next:'Best next training',fix:'Fix these mistakes now',dashboard:'Return to dashboard',clean:'No typing-pattern errors detected in this session.',focus:'Your next drill should focus on',keepGoing:'Excellent control. Continue with a faster session.',diagnoses:{shift:'Shift-layer confusion',tone:'Thai tone-mark confusion',vowel:'Thai vowel confusion',adjacent:'Adjacent-key slips',substitution:'Character substitution'}},
'zh-CN':{reportEye:'VIP 自适应教练',reportTitle:'本次练习诊断',why:'错误原因',next:'最佳下一步训练',fix:'立即修复这些错误',dashboard:'返回仪表盘',clean:'本次没有发现可重复的输入错误模式。',focus:'下一组训练应重点练习',keepGoing:'控制非常稳定，建议提高速度继续训练。',diagnoses:{shift:'Shift 键层混淆',tone:'泰语声调符号混淆',vowel:'泰语元音混淆',adjacent:'相邻键误触',substitution:'字符替换错误'}},
'zh-TW':{reportEye:'VIP 自適應教練',reportTitle:'本次練習診斷',why:'錯誤原因',next:'最佳下一步訓練',fix:'立即修復這些錯誤',dashboard:'返回儀表板',clean:'本次沒有發現可重複的輸入錯誤模式。',focus:'下一組訓練應重點練習',keepGoing:'控制非常穩定，建議提高速度繼續訓練。',diagnoses:{shift:'Shift 鍵層混淆',tone:'泰語聲調符號混淆',vowel:'泰語母音混淆',adjacent:'相鄰鍵誤觸',substitution:'字元替換錯誤'}},
th:{reportEye:'โค้ชปรับตัว VIP',reportTitle:'การวิเคราะห์การฝึกครั้งนี้',why:'สาเหตุของข้อผิดพลาด',next:'การฝึกถัดไปที่ดีที่สุด',fix:'แก้ข้อผิดพลาดเหล่านี้ทันที',dashboard:'กลับแดชบอร์ด',clean:'ไม่พบรูปแบบข้อผิดพลาดซ้ำในเซสชันนี้',focus:'แบบฝึกถัดไปควรเน้น',keepGoing:'ควบคุมได้ดีมาก ลองเพิ่มความเร็วต่อไป',diagnoses:{shift:'สับสนชั้นปุ่ม Shift',tone:'สับสนเครื่องหมายวรรณยุกต์',vowel:'สับสนสระไทย',adjacent:'กดปุ่มข้างเคียงผิด',substitution:'แทนที่ตัวอักษรผิด'}},
ru:{reportEye:'Адаптивный VIP-тренер',reportTitle:'Диагностика тренировки',why:'Почему возникли ошибки',next:'Лучшая следующая тренировка',fix:'Исправить ошибки сейчас',dashboard:'Вернуться на панель',clean:'Повторяющихся ошибок в этой сессии не обнаружено.',focus:'В следующем упражнении сосредоточьтесь на',keepGoing:'Отличный контроль. Продолжайте на более высокой скорости.',diagnoses:{shift:'Ошибка слоя Shift',tone:'Путаница тайских тоновых знаков',vowel:'Путаница тайских гласных',adjacent:'Промах по соседней клавише',substitution:'Замена символа'}}
}
export const coachCopy=coaching[locale]
Object.assign(coachCopy,{
en:{recipientName:'Name on certificate',namePlaceholder:'Enter the recipient name',digitalTitle:'Digital certificate',digitalText:'Download a print-ready verified PDF with your name, result, date and certificate ID.',downloadFree:'Download free PDF certificate',preparingPdf:'Preparing PDF…',pdfReady:'PDF ready to download',pdfFailed:'PDF generation failed. Please refresh and try again.',paperTitle:'Printed certificate',paperText:'Professionally printed and delivered after payment verification.',thailandOnly:'Delivery is available within Thailand only. International shipping is not supported.',orderPaper:'Order printed certificate',paperEyebrow:'Printed certificate order',checkoutText:'Pay the ฿299 printing and delivery fee through our secure checkout.',shippingThailand:'Shipping address must be in Thailand.',addressAfterPayment:'Recipient address and phone are collected only after successful payment.',orderEmail:'A confirmed order is emailed to the ThaiType team.',payShipping:'Pay ฿299 delivery fee',paymentVerified:'Payment verified. Enter the Thailand delivery details.',phone:'Recipient phone',address:'Street address and district',province:'Province',postal:'Postal code',country:'Destination country',submitOrder:'Submit confirmed order',checkoutUnavailable:'Secure payment is not connected yet. Configure the certificate checkout API before launch.',orderSuccess:'Order received. We will email the order confirmation shortly.',orderFailed:'The order could not be submitted. Please try again.'},
'zh-CN':{recipientName:'证书姓名',namePlaceholder:'请输入证书上的姓名',digitalTitle:'电子证书',digitalText:'免费下载包含姓名、成绩、日期和认证编号的高清打印版 PDF。',downloadFree:'免费下载 PDF 证书',preparingPdf:'正在生成 PDF…',pdfReady:'PDF 已生成，可以下载',pdfFailed:'PDF 生成失败，请刷新后重试。',paperTitle:'纸质证书',paperText:'支付验证成功后，由我们专业打印并寄送。',thailandOnly:'仅支持泰国境内配送，不支持泰国境外邮寄。',orderPaper:'订购纸质证书',paperEyebrow:'纸质证书订单',checkoutText:'通过安全支付渠道支付 ฿299 打印和快递费用。',shippingThailand:'收件地址必须位于泰国境内。',addressAfterPayment:'支付成功后才会收集收件地址和电话。',orderEmail:'确认订单将通过邮件发送给 ThaiType 团队。',payShipping:'支付 ฿299 快递费',paymentVerified:'支付已验证，请填写泰国境内收件信息。',phone:'收件人电话',address:'详细地址和区县',province:'府／省',postal:'邮政编码',country:'配送国家',submitOrder:'提交已支付订单',checkoutUnavailable:'安全支付尚未接入，请在上线前配置证书支付接口。',orderSuccess:'订单已收到，我们稍后会发送确认邮件。',orderFailed:'订单提交失败，请重试。'},
'zh-TW':{recipientName:'證書姓名',namePlaceholder:'請輸入證書上的姓名',digitalTitle:'電子證書',digitalText:'免費取得高清、附認證編號的 PNG 證書。',downloadFree:'免費下載證書',paperTitle:'紙本證書',paperText:'付款驗證成功後，由我們專業印製並寄送。',thailandOnly:'僅支援泰國境內配送，不支援海外郵寄。',orderPaper:'訂購紙本證書',paperEyebrow:'紙本證書訂單',checkoutText:'透過安全付款管道支付 ฿299 印製和快遞費用。',shippingThailand:'收件地址必須位於泰國境內。',addressAfterPayment:'付款成功後才會收集地址和電話。',orderEmail:'確認訂單將透過電子郵件傳送給 ThaiType 團隊。',payShipping:'支付 ฿299 快遞費',paymentVerified:'付款已驗證，請填寫泰國境內收件資料。',phone:'收件人電話',address:'詳細地址和區縣',province:'府／省',postal:'郵遞區號',country:'配送國家',submitOrder:'提交已付款訂單',checkoutUnavailable:'安全付款尚未串接，請在上線前設定證書付款介面。',orderSuccess:'訂單已收到，我們稍後會寄送確認郵件。',orderFailed:'訂單提交失敗，請重試。'},
th:{recipientName:'ชื่อบนใบรับรอง',namePlaceholder:'กรอกชื่อผู้รับใบรับรอง',digitalTitle:'ใบรับรองดิจิทัล',digitalText:'ดาวน์โหลดใบรับรอง PNG ความละเอียดสูงพร้อมรหัสยืนยันได้ฟรี',downloadFree:'ดาวน์โหลดใบรับรองฟรี',paperTitle:'ใบรับรองฉบับพิมพ์',paperText:'พิมพ์อย่างมืออาชีพและจัดส่งหลังตรวจสอบการชำระเงิน',thailandOnly:'จัดส่งเฉพาะภายในประเทศไทย ไม่รองรับการจัดส่งต่างประเทศ',orderPaper:'สั่งใบรับรองฉบับพิมพ์',paperEyebrow:'คำสั่งซื้อใบรับรองฉบับพิมพ์',checkoutText:'ชำระค่าพิมพ์และจัดส่ง ฿299 ผ่านระบบชำระเงินที่ปลอดภัย',shippingThailand:'ที่อยู่จัดส่งต้องอยู่ในประเทศไทย',addressAfterPayment:'ระบบจะขอที่อยู่และโทรศัพท์หลังชำระเงินสำเร็จเท่านั้น',orderEmail:'คำสั่งซื้อที่ยืนยันแล้วจะส่งอีเมลถึงทีม ThaiType',payShipping:'ชำระค่าจัดส่ง ฿299',paymentVerified:'ยืนยันการชำระเงินแล้ว กรุณากรอกข้อมูลจัดส่งในประเทศไทย',phone:'โทรศัพท์ผู้รับ',address:'ที่อยู่ ถนน เขต/อำเภอ',province:'จังหวัด',postal:'รหัสไปรษณีย์',country:'ประเทศปลายทาง',submitOrder:'ส่งคำสั่งซื้อที่ชำระแล้ว',checkoutUnavailable:'ยังไม่ได้เชื่อมต่อระบบชำระเงิน โปรดตั้งค่า API ก่อนเปิดใช้งานจริง',orderSuccess:'ได้รับคำสั่งซื้อแล้ว เราจะส่งอีเมลยืนยันในภายหลัง',orderFailed:'ส่งคำสั่งซื้อไม่สำเร็จ โปรดลองอีกครั้ง'},
ru:{recipientName:'Имя на сертификате',namePlaceholder:'Введите имя получателя',digitalTitle:'Цифровой сертификат',digitalText:'Бесплатно скачайте проверяемый PNG высокого разрешения.',downloadFree:'Скачать бесплатно',paperTitle:'Печатный сертификат',paperText:'Профессиональная печать и доставка после подтверждения оплаты.',thailandOnly:'Доставка только по Таиланду. Международная доставка недоступна.',orderPaper:'Заказать печатный сертификат',paperEyebrow:'Заказ печатного сертификата',checkoutText:'Оплатите ฿299 за печать и доставку через защищённую оплату.',shippingThailand:'Адрес доставки должен находиться в Таиланде.',addressAfterPayment:'Адрес и телефон запрашиваются только после успешной оплаты.',orderEmail:'Подтверждённый заказ отправляется команде ThaiType по email.',payShipping:'Оплатить доставку ฿299',paymentVerified:'Оплата подтверждена. Укажите адрес доставки в Таиланде.',phone:'Телефон получателя',address:'Улица, район и адрес',province:'Провинция',postal:'Почтовый индекс',country:'Страна доставки',submitOrder:'Отправить оплаченный заказ',checkoutUnavailable:'Безопасная оплата ещё не подключена. Настройте API перед запуском.',orderSuccess:'Заказ получен. Подтверждение будет отправлено по email.',orderFailed:'Не удалось отправить заказ. Повторите попытку.'}
}[locale])
export function selector(){return`<select id="language-select" aria-label="Language">${Object.entries(labels).map(([k,v])=>`<option value="${k}"${k===locale?' selected':''}>${v}</option>`).join('')}</select>`}
export function bind(){document.documentElement.lang=locale;document.title=copy.title;document.querySelector('#language-select').onchange=e=>{localStorage.setItem('thaitype-locale',e.target.value);location.reload()}}
