import './assessment.css'
import './language-switch.css'
import {load,save,makeId,stamp} from './recruitment-store.js'
import {localize,selector,tr} from './product-i18n.js'

let db=load(),stage='intro',candidate,project,template,questions=[],questionIndex=0,startAt=0,questionStart=0,events=[],anomalies=[],timer,remaining=0,blurStarted=0
const app=document.querySelector('#app'),token=new URLSearchParams(location.search).get('token')
candidate=db.candidates.find(x=>x.token===token);project=candidate&&db.projects.find(x=>x.id===candidate.projectId);template=project&&db.templates.find(x=>x.id===project.templateId);questions=template?template.questionIds.map(id=>db.questions.find(x=>x.id===id)).filter(Boolean):[]
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))

function shell(content){app.innerHTML=`<header class="assess-head wrap"><div class="brand">ThaiType <span>Business</span></div><div class="actions">${selector()}<div class="secure">标准化招聘测评 · 行为记录已开启</div></div></header><main class="stage wrap">${content}</main>`;localize(app)}
function invalid(){shell(`<div class="error"><h1>测评链接无效</h1><p>链接可能已经失效或不属于当前浏览器中的企业数据。</p></div>`)}
function intro(){if(!candidate||!project||!template)return invalid();if(candidate.status==='已完成')return complete(db.results.find(x=>x.id===candidate.resultId));const proctor=db.proctoring?.enabled?`<div class="proctor-notice"><b>本次测评启用了高级监考</b><p>${db.proctoring.cameraSnapshots?'摄像头定时截图 · ':''}${db.proctoring.facePresence?'人脸存在检测 · ':''}${db.proctoring.microphone?'麦克风异常检测 · ':''}资料保留 ${db.proctoring.retentionDays} 天。您可以联系招聘企业申请非摄像头替代方案。</p></div>`:'';shell(`<section class="intro"><div><div class="eyebrow">CANDIDATE ASSESSMENT</div><h1>${esc(template.name)}<br>泰语输入能力测评</h1><p>${esc(candidate.name)}，您好。本测评用于评估与岗位直接相关的泰语输入速度、准确率、稳定性和结果可信度，不使用国家、年龄或性别参与评分。</p>${proctor}<label class="consent"><input id="consent" type="checkbox"> <span>我已阅读测试说明，同意记录按键时间、页面离开、粘贴和设备信息用于本次招聘测评。数据保留 ${db.organization.dataRetentionDays} 天。</span></label><button class="btn" id="continue" disabled>进行设备检查</button></div><aside class="facts"><div><small>招聘企业</small><b>${esc(db.organization.name)}</b></div><div><small>招聘项目</small><b>${esc(project.name)}</b></div><div><small>预计时长</small><b>${template.duration} 分钟</b></div><div><small>题目数量</small><b>${questions.length} 道</b></div><div><small>测试次数</small><b>1 次正式提交</b></div></aside></section>`);document.querySelector('#consent').onchange=e=>document.querySelector('#continue').disabled=!e.target.checked;document.querySelector('#continue').onclick=()=>{stage='check';render()}}
function check(){const thaiSupport=/[ก-๙]/u.test('ภาษาไทย'),desktop=innerWidth>=700,cameraNeeded=db.proctoring?.enabled&&(db.proctoring.photo||db.proctoring.cameraSnapshots||db.proctoring.facePresence);shell(`<section><div class="eyebrow">SYSTEM CHECK</div><h1>正式开始前检查</h1><p>请使用电脑和泰语键盘完成测评。开始后请勿切换窗口、复制或粘贴。</p><div class="checklist"><div class="check"><span>现代浏览器与本地存储</span><b class="ok">通过</b></div><div class="check"><span>泰语字符显示</span><b class="${thaiSupport?'ok':'warn'}">${thaiSupport?'通过':'需检查'}</b></div><div class="check"><span>电脑端窗口</span><b class="${desktop?'ok':'warn'}">${desktop?'通过':'建议使用电脑'}</b></div><div class="check"><span>网络中断恢复</span><b class="ok">本地会话已就绪</b></div>${cameraNeeded?'<div class="check"><span>摄像头授权</span><b class="warn">开始时请求</b></div>':''}</div><button class="btn secondary" id="practice">先做练习</button> <button class="btn" id="start">开始正式测评</button></section>`);document.querySelector('#practice').onclick=practice;document.querySelector('#start').onclick=start}
function practice(){const text='การพิมพ์ภาษาไทย';shell(`<section class="assessment"><div class="test-head"><b>练习题 · 不计分</b></div><div class="test-body"><p>请使用泰语键盘输入下面内容：</p><div class="source" lang="th">${text}</div><textarea class="typing" id="practice-input" lang="th" autocomplete="off" spellcheck="false"></textarea><div class="test-foot"><span>练习用于确认输入法，不记录分数。</span><button class="btn" id="practice-done">完成练习</button></div></div></section>`);document.querySelector('#practice-done').onclick=()=>{const value=document.querySelector('#practice-input').value;if(!/[ก-๙]/u.test(value))return alert(tr('未检测到泰语输入，请切换到泰语键盘后重试。'));check()}}
async function start(){const p=db.proctoring||{};if(!candidate.creditCharged&&db.organization.credits<=0)return alert(tr('企业测评额度不足，请联系招聘负责人。'));let cameraGranted=false;if(p.enabled&&(p.photo||p.cameraSnapshots||p.facePresence)){try{const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:!!p.microphone});cameraGranted=true;stream.getTracks().forEach(track=>track.stop())}catch{return alert(tr('无法获得监考设备授权，请联系招聘企业申请替代方案。'))}}if(!candidate.creditCharged){candidate.creditCharged=true;db.organization.credits--;db.billing?.transactions.unshift({id:makeId('txn'),type:'候选人正式测评',credits:-1,amount:0,status:'已扣除',createdAt:new Date().toISOString()})}candidate.status='已开始';startAt=Date.now();remaining=template.duration*60;events=[];anomalies=[];questionIndex=0;db.sessions.push({id:makeId('session'),candidateId:candidate.id,startedAt:new Date().toISOString(),consent:true,proctoringEnabled:!!p.enabled,cameraGranted,policyVersion:db.privacy?.policyVersion||'1.0'});save(db);showQuestion();timer=setInterval(tick,1000);window.addEventListener('blur',onBlur);document.addEventListener('visibilitychange',onVisibility);document.addEventListener('fullscreenchange',onFullscreen)}
function showQuestion(){const q=questions[questionIndex];questionStart=Date.now();shell(`<section class="assessment"><div class="test-head"><b>${esc(project.name)}</b><span class="timer" id="timer">${time(remaining)}</span></div><div class="progress"><i style="width:${questionIndex/questions.length*100}%"></i></div><div class="test-body"><div class="question-meta"><span>第 ${questionIndex+1} / ${questions.length} 题 · ${esc(q.type)}</span><span>${esc(q.title)}</span></div><div class="source" id="source" lang="th">${renderSource(q.text,'')}</div><textarea class="typing" id="typing" lang="th" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" placeholder="请在这里输入泰语内容…"></textarea><div class="test-foot"><span>系统记录首次输入、修改和异常行为。</span><button class="btn" id="next" disabled>${questionIndex===questions.length-1?'提交测评':'下一题'}</button></div></div></section>`);const input=document.querySelector('#typing');input.focus();input.addEventListener('beforeinput',e=>events.push({at:Date.now()-startAt,type:e.inputType,data:e.data,question:questionIndex}));input.addEventListener('paste',e=>{e.preventDefault();flag('检测到粘贴操作',3)});input.addEventListener('input',e=>{const value=e.target.value,source=q.text;document.querySelector('#source').innerHTML=renderSource(source,value);document.querySelector('#next').disabled=value.length<Math.max(1,source.length*.6);if(value.length>source.length*1.5)e.target.value=value.slice(0,source.length*1.5)});document.querySelector('#next').onclick=nextQuestion}
function renderSource(source,input){return [...source].map((char,i)=>`<span class="${i<input.length?(input[i]===char?'correct':'wrong'):i===input.length?'current':''}">${esc(char)}</span>`).join('')}
function nextQuestion(){const q=questions[questionIndex],value=document.querySelector('#typing').value;events.push({at:Date.now()-startAt,type:'answer',question:questionIndex,value,source:q.text,duration:Date.now()-questionStart});if(questionIndex<questions.length-1){questionIndex++;showQuestion()}else finish()}
function tick(){remaining--;document.querySelector('#timer')&&(document.querySelector('#timer').textContent=time(remaining));if(remaining<=0)finish()}
const time=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.max(0,s%60)).padStart(2,'0')}`
function onBlur(){blurStarted=Date.now();flag('离开测评窗口',1)}
function onVisibility(){if(document.hidden)flag('切换浏览器页面',2)}
function onFullscreen(){if(!document.fullscreenElement)flag('退出全屏模式',1)}
function flag(type,weight){anomalies.push({type,at:Date.now()-startAt,weight});const toast=document.createElement('div');toast.className='toast';toast.textContent=`${tr('已记录：')} ${tr(type)}`;document.body.append(toast);setTimeout(()=>toast.remove(),2200)}
function similarity(source,value){let correct=0;const length=Math.max(source.length,value.length);for(let i=0;i<Math.min(source.length,value.length);i++)if(source[i]===value[i])correct++;return length?correct/length*100:0}
function finish(){clearInterval(timer);window.removeEventListener('blur',onBlur);document.removeEventListener('visibilitychange',onVisibility);document.removeEventListener('fullscreenchange',onFullscreen);const answers=events.filter(x=>x.type==='answer');if(!answers.length)return invalid();const typed=answers.reduce((n,x)=>n+[...x.value].length,0),seconds=Math.max(1,(Date.now()-startAt)/1000),rawSpeed=Math.round(typed/(seconds/60)),accuracy=answers.reduce((n,x)=>n+similarity(x.source,x.value),0)/answers.length,corrections=events.filter(x=>x.type?.includes('delete')).length,firstAccuracy=Math.max(0,accuracy-corrections/Math.max(1,typed)*100),durations=answers.map(x=>x.duration),avg=durations.reduce((a,b)=>a+b,0)/durations.length,variation=durations.reduce((n,x)=>n+Math.abs(x-avg),0)/durations.length,stability=Math.max(50,Math.round(100-variation/Math.max(avg,1)*100)),integrity=Math.max(40,100-anomalies.reduce((n,x)=>n+x.weight*4,0)),speedScore=Math.min(100,rawSpeed/template.minSpeed*85),accuracyScore=Math.min(100,accuracy/template.minAccuracy*90),score=Math.round(speedScore*template.weights.speed/100+accuracyScore*template.weights.accuracy/100+stability*template.weights.stability/100+integrity*template.weights.integrity/100),recommendation=score>=85&&accuracy>=template.minAccuracy?'推荐进入下一轮':score>=70?'建议人工复核':score>=60?'建议重新测试':'不符合当前岗位标准',integrityLabel=integrity>=90?'高可信':integrity>=75?'存在轻微异常':integrity>=60?'建议人工复核':'建议重新测试';const r={id:makeId('r'),candidateId:candidate.id,projectId:project.id,completedAt:new Date().toISOString(),speed:rawSpeed,rawSpeed,accuracy:+accuracy.toFixed(1),firstAccuracy:+firstAccuracy.toFixed(1),stability,completion:Math.round(answers.length/questions.length*100),score,integrity,integrityLabel,recommendation,errors:{wrong:Math.round(typed*(100-accuracy)/100),missing:0,extra:0,corrections},anomalies,durationSeconds:Math.round(seconds),events};db.results.push(r);candidate.status='已完成';candidate.resultId=r.id;if(anomalies.length||db.proctoring?.enabled)db.reviewQueue.unshift({id:makeId('review'),candidateId:candidate.id,reason:anomalies.length?`${anomalies.length} 项行为异常`:'高级监考资料待抽查',risk:integrity>=85?'低':integrity>=70?'中':'高',status:'待复核',reviewer:null,createdAt:new Date().toISOString()});db.notifications?.logs.unshift({id:makeId('nl'),type:'完成通知',recipient:db.currentUser.email,status:'模拟送达',createdAt:new Date().toISOString()});stamp(db,`${candidate.name} 完成招聘测评`);complete(r)}
function complete(r){shell(`<section class="complete"><div class="eyebrow">ASSESSMENT COMPLETE</div><h1>测评已经安全提交</h1><p>感谢您完成测评。招聘企业将根据岗位标准和完整报告进行人工复核。</p><div class="score">${r.score}</div><b>综合评分</b><div class="metrics"><div><small>有效速度</small><b>${r.speed}</b></div><div><small>准确率</small><b>${r.accuracy}%</b></div><div><small>稳定性</small><b>${r.stability}</b></div><div><small>结果可信度</small><b>${esc(r.integrityLabel)}</b></div></div><p><b>${esc(r.recommendation)}</b></p><small>报告编号：${esc(r.id)} · 最终招聘决定由企业HR作出</small></section>`)}
function render(){({intro,check,practice}[stage]||intro)()}
render()
