import './portal.css'
import './language-switch.css'
import './enterprise.css'
import './portal-layout-fix.css'
import './phase20.css'
import {load,save,reset,makeId,stamp,inviteUrl,csv} from './recruitment-store.js'
import {localize,selector,tr} from './product-i18n.js'

let db=load(),view='dashboard',selectedReport=null
const app=document.querySelector('#app')
const canEdit=()=>!['只读成员','面试官'].includes(db.currentUser.role)
const template=id=>db.templates.find(x=>x.id===id)
const project=id=>db.projects.find(x=>x.id===id)
const result=id=>db.results.find(x=>x.id===id)
const candidate=id=>db.candidates.find(x=>x.id===id)
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))
const badge=value=>`<span class="badge ${/复测|邀请/.test(value)?'warn':/淘汰|不符合/.test(value)?'bad':''}">${esc(value)}</span>`
const btn=(label,action,id='',kind='secondary')=>`<button class="btn small ${kind}" data-action="${action}" data-id="${id}">${label}</button>`

function shell(content,title){
  const menus=[['dashboard','总览'],['projects','招聘项目'],['candidates','候选人'],['templates','岗位模板'],['questions','题库'],['results','结果中心'],['proctoring','高级监考'],['compliance','隐私与合规'],['billing','套餐与账单'],['notifications','通知中心'],['integrations','企业集成'],['validation','测试与校准'],['pilots','企业试点'],['operations','上线与运营'],['members','团队与权限'],['settings','企业设置']]
  app.innerHTML=`<div class="layout"><aside class="sidebar"><a href="/" class="logo">ThaiType <span>Business</span></a><div class="org"><small>${esc(db.organization.plan)}</small><strong>${esc(db.organization.name)}</strong></div><nav class="menu">${menus.map(([id,name])=>`<button data-view="${id}" class="${view===id?'active':''}">${name}</button>`).join('')}</nav><div class="side-foot">剩余测评额度：<b>${db.organization.credits}</b><br>数据保留 ${db.organization.dataRetentionDays} 天</div></aside><main class="main"><header class="topbar"><h1>${title}</h1><div class="actions">${selector()}<select class="role-switch" id="role-switch">${['企业管理员','招聘经理','面试官','只读成员'].map(x=>`<option ${x===db.currentUser.role?'selected':''}>${x}</option>`).join('')}</select><span class="user">${esc(db.currentUser.name)} · ${esc(db.currentUser.role)}</span></div></header>${content}</main></div><div id="modal" class="modal" hidden></div>`
  localize(app)
  bindGlobal()
}

function pageHead(title,text,action=''){return `<div class="page-head"><div><h2>${title}</h2><p>${text}</p></div>${action}</div>`}

function dashboard(){
  const completed=db.candidates.filter(x=>x.status==='已完成').length,invited=db.candidates.filter(x=>x.status==='已邀请').length
  const avg=db.results.length?Math.round(db.results.reduce((n,x)=>n+x.score,0)/db.results.length):0
  const funnel=[['候选人',db.candidates.length],['已邀请',db.candidates.filter(x=>x.invitedAt).length],['已开始',db.candidates.filter(x=>['已开始','已完成'].includes(x.status)).length],['已完成',completed]]
  shell(`<section class="page">${pageHead('招聘测评总览','把岗位标准、候选人和招聘结论放在同一个工作台。',canEdit()?`<button class="btn" data-action="new-project">创建招聘项目</button>`:'')}
  <div class="kpis"><div class="kpi"><small>进行中项目</small><b>${db.projects.filter(x=>x.status==='进行中').length}</b><em>统一岗位标准</em></div><div class="kpi"><small>待完成测评</small><b>${invited}</b><em>可发送提醒</em></div><div class="kpi"><small>已完成</small><b>${completed}</b><em>形成决策报告</em></div><div class="kpi"><small>平均综合分</small><b>${avg}</b><em>满分 100</em></div></div>
  <div class="grid-2"><div class="panel"><h3>招聘测评漏斗</h3><div class="funnel">${funnel.map(([name,n])=>`<div><i style="height:${Math.max(8,n*28)}px"></i><b>${n}</b><br>${name}</div>`).join('')}</div></div><div class="panel"><h3>最近操作</h3><div class="activity">${db.audit.slice(0,5).map(x=>`<div>${esc(x.action)}<small>${new Date(x.at).toLocaleString()}</small></div>`).join('')}</div></div></div></section>`,'招聘测评控制台')
}

function projects(){
  shell(`<section class="page">${pageHead('招聘项目','每个项目固定一套岗位标准，确保候选人公平比较。',canEdit()?`<button class="btn" data-action="new-project">创建项目</button>`:'')}<div class="table-wrap"><table><thead><tr><th>项目</th><th>岗位模板</th><th>负责人</th><th>截止日期</th><th>候选人</th><th>状态</th><th>操作</th></tr></thead><tbody>${db.projects.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td>${esc(template(p.templateId)?.name)}</td><td>${esc(p.owner)}</td><td>${esc(p.deadline)}</td><td>${db.candidates.filter(c=>c.projectId===p.id).length}</td><td>${badge(p.status)}</td><td>${canEdit()?btn('添加候选人','new-candidate',p.id):''}</td></tr>`).join('')}</tbody></table></div></section>`,'招聘项目')
}

function candidates(){
  shell(`<section class="page">${pageHead('候选人','管理邀请、状态、备注和专属测评链接。',canEdit()?`<button class="btn" data-action="new-candidate">添加候选人</button>`:'')}<div class="filters"><input id="candidate-search" placeholder="搜索姓名或邮箱"><select id="candidate-status"><option value="">全部状态</option>${['待邀请','已邀请','已开始','已完成','需复测','进入下一轮','淘汰','已录用'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr><th>候选人</th><th>项目</th><th>状态</th><th>分数</th><th>专属测评链接</th><th>操作</th></tr></thead><tbody id="candidate-rows">${candidateRows(db.candidates)}</tbody></table></div></section>`,'候选人管理')
}
function candidateRows(rows){return rows.map(c=>{const r=result(c.resultId);return `<tr><td><b>${esc(c.name)}</b><br><small>${esc(c.email)}</small></td><td>${esc(project(c.projectId)?.name)}</td><td>${badge(c.status)}</td><td>${r?`<span class="score">${r.score}</span>`:'—'}</td><td class="invite">${esc(inviteUrl(c.token))}</td><td><div class="actions">${btn('复制链接','copy-link',c.id)}${r?btn('查看报告','report',r.id):''}${canEdit()?btn('更新状态','status',c.id):''}</div></td></tr>`}).join('')||`<tr><td colspan="6" class="empty">暂无候选人</td></tr>`}

function templatesView(){
  shell(`<section class="page">${pageHead('岗位模板','按岗位定义题目、合格线和评分权重。',canEdit()?`<button class="btn" data-action="new-template">自定义模板</button>`:'')}<div class="cards">${db.templates.map(t=>`<article class="card"><span>${badge(t.status)} · V${t.version}</span><h3>${esc(t.name)}</h3><p>${esc(t.description)}</p><dl><div><dt>最低速度</dt><dd>${t.minSpeed} 字符/分钟</dd></div><div><dt>最低准确率</dt><dd>${t.minAccuracy}%</dd></div><div><dt>测试时长</dt><dd>${t.duration} 分钟</dd></div><div><dt>题目数量</dt><dd>${t.questionIds.length} 道</dd></div></dl><div class="actions">${canEdit()?btn('复制模板','clone-template',t.id)+btn('编辑','edit-template',t.id):''}</div></article>`).join('')}</div></section>`,'岗位与评分标准')
}

function questionsView(){
  shell(`<section class="page">${pageHead('企业题库','覆盖抄写、业务场景、结构化录入和稳定性测试。',canEdit()?`<button class="btn" data-action="new-question">添加题目</button>`:'')}<div class="table-wrap"><table><thead><tr><th>题目</th><th>题型</th><th>行业</th><th>难度</th><th>泰文长度</th><th>状态</th></tr></thead><tbody>${db.questions.map(q=>`<tr><td><b>${esc(q.title)}</b><br><small lang="th">${esc(q.text.slice(0,48))}…</small></td><td>${esc(q.type)}</td><td>${esc(q.industry)}</td><td>${esc(q.difficulty)}</td><td>${[...q.text].length}</td><td>${badge(q.status)}</td></tr>`).join('')}</tbody></table></div></section>`,'题库与组卷')
}

function results(){
  const rows=db.results.map(r=>({r,c:candidate(r.candidateId),p:project(r.projectId)}))
  shell(`<section class="page">${pageHead('结果中心','按岗位标准排序，快速识别可推进、需复测和高风险候选人。',`<div class="actions"><button class="btn secondary" data-action="export">导出 CSV</button></div>`)}<div class="table-wrap"><table><thead><tr><th>候选人</th><th>项目</th><th>综合分</th><th>有效速度</th><th>准确率</th><th>可信度</th><th>招聘建议</th><th>操作</th></tr></thead><tbody>${rows.map(({r,c,p})=>`<tr><td><b>${esc(c?.name)}</b></td><td>${esc(p?.name)}</td><td><span class="score">${r.score}</span></td><td>${r.speed}</td><td>${r.accuracy}%</td><td>${badge(r.integrityLabel)}</td><td>${badge(r.recommendation)}</td><td>${btn('报告','report',r.id)}</td></tr>`).join('')}</tbody></table></div></section>`,'测评结果')
}

function proctoring(){const p=db.proctoring;const check=(name,label,help)=>`<label class="setting-row"><span><b>${label}</b><small>${help}</small></span><input type="checkbox" name="${name}" ${p[name]?'checked':''}></label>`;shell(`<section class="page">${pageHead('高级监考与人工复核','监考能力由企业按项目启用，候选人必须提前知情并明确授权。')}<div class="grid-2"><form id="proctoring-form" class="panel settings-list"><h3>监考策略</h3>${check('enabled','启用高级监考','关闭时仍保留页面切换和粘贴等基础行为检测。')}${check('photo','测试前拍照','开始测试前采集一张候选人照片。')}${check('cameraSnapshots','摄像头定时截图','按设定间隔采集画面并进入人工复核。')}${check('facePresence','人脸存在检测','标记长时间无人出现在画面中的情况。')}${check('multipleFaces','多人入镜检测','检测到多张人脸时只标记风险，不自动判定作弊。')}${check('idVerification','证件核验','允许企业要求候选人提交证件进行人工核验。')}${check('microphone','麦克风异常检测','记录异常声音事件，不保存完整音频。')}${check('screenRecording','屏幕录制','高敏感能力，仅建议受监管岗位按需启用。')}${check('alternativeAllowed','允许非摄像头替代方案','候选人可以申请人工安排或现场测评。')}<label>截图间隔（秒）<input name="snapshotInterval" type="number" min="30" value="${p.snapshotInterval}"></label><label>监考资料保留（天）<input name="retentionDays" type="number" min="1" value="${p.retentionDays}"></label><button class="btn" type="submit">保存监考策略</button></form><div class="panel"><h3>人工复核队列</h3><div class="review-list">${db.reviewQueue.map(x=>`<article><div><b>${esc(candidate(x.candidateId)?.name||x.candidateId)}</b><small>${esc(x.reason)}</small></div>${badge(x.risk+'风险')} ${badge(x.status)}</article>`).join('')||'<p>当前没有待复核记录</p>'}</div><p class="muted">系统只提供风险证据，最终结论必须由获得授权的HR作出。</p></div></div></section>`,'高级监考')}

function compliance(){const p=db.privacy;shell(`<section class="page">${pageHead('隐私、公平性与合规','管理候选人授权、数据生命周期和评分公平性。',`<button class="btn" data-action="privacy-request">新建隐私请求</button>`)}<div class="kpis"><div class="kpi"><small>隐私政策版本</small><b>${p.policyVersion}</b><em>授权记录可审计</em></div><div class="kpi"><small>数据保留期限</small><b>${p.retentionDays}</b><em>天</em></div><div class="kpi"><small>待处理请求</small><b>${p.requests.filter(x=>x.status!=='已完成').length}</b><em>导出或删除</em></div><div class="kpi"><small>评分排除字段</small><b>${p.excludedFields.length}</b><em>${p.excludedFields.join('、')}</em></div></div><div class="grid-2"><div class="panel"><h3>合规控制</h3><div class="settings-list">${[['candidateExport','候选人数据导出'],['candidateDeletion','候选人删除申请'],['autoDelete','到期自动删除'],['fairnessGuard','公平性评分保护']].map(([key,label])=>`<label class="setting-row"><span><b>${label}</b></span><input type="checkbox" ${p[key]?'checked':''} disabled></label>`).join('')}</div><p class="muted">国家、年龄和性别永远不会进入招聘评分。</p></div><div class="panel"><h3>隐私请求</h3><div class="review-list">${p.requests.map(x=>`<article><div><b>${esc(x.candidate)}</b><small>${new Date(x.createdAt).toLocaleDateString()} · ${esc(x.type)}</small></div>${badge(x.status)}</article>`).join('')}</div></div></div></section>`,'隐私与合规')}

function billing(){const b=db.billing;shell(`<section class="page">${pageHead('套餐、额度与账单','按测评次数透明计费；候选人正式开始后才扣除额度。')}<div class="kpis"><div class="kpi"><small>当前套餐</small><b>${esc(b.plan)}</b><em>${esc(b.renewal)}</em></div><div class="kpi"><small>可用测评额度</small><b>${db.organization.credits}</b><em>次</em></div><div class="kpi"><small>下次账单日期</small><b class="date-kpi">${esc(b.nextBillingDate)}</b><em>${b.currency}</em></div><div class="kpi"><small>本月使用</small><b>${db.results.length}</b><em>次测评</em></div></div><h3>测评额度包</h3><div class="cards">${b.packages.map(x=>`<article class="card"><span>${x.credits} 次测评</span><h3>${esc(x.name)}</h3><div class="price">฿${x.price.toLocaleString()}</div><p>适合${x.credits<=50?'小型团队或首次试点':x.credits<=200?'持续招聘团队':'大型企业年度招聘'}。</p>${canEdit()?btn('模拟购买','buy-package',x.id,''):''}</article>`).join('')}</div><div class="panel billing-log"><h3>额度与交易记录</h3>${b.transactions.map(x=>`<div><span>${esc(x.type)} · ${new Date(x.createdAt).toLocaleString()}</span><b>${x.credits>0?'+':''}${x.credits} / ฿${x.amount.toLocaleString()}</b>${badge(x.status)}</div>`).join('')}</div></section>`,'套餐与账单')}

function notifications(){const n=db.notifications;shell(`<section class="page">${pageHead('通知中心','管理候选人邀请、提醒和企业内部通知。',canEdit()?`<button class="btn" data-action="send-test">发送测试通知</button>`:'')}<div class="grid-2"><div class="panel"><h3>通知模板</h3><div class="template-list">${n.templates.map(x=>`<article><div><b>${esc(x.type)}</b><small>${esc(x.subject)}</small></div><span>${badge(x.enabled?'已启用':'已停用')}</span>${canEdit()?btn(x.enabled?'停用':'启用','toggle-notification',x.id):''}</article>`).join('')}</div></div><div class="panel"><h3>发送记录</h3><div class="review-list">${n.logs.map(x=>`<article><div><b>${esc(x.type)}</b><small>${esc(x.recipient)} · ${new Date(x.createdAt).toLocaleString()}</small></div>${badge(x.status)}</article>`).join('')}</div><p class="muted">当前为本地模拟发送；正式环境需要配置邮件服务商和发件域名。</p></div></div></section>`,'通知中心')}

function integrations(){const i=db.integrations;shell(`<section class="page">${pageHead('API与企业集成','通过受控API、Webhook、SSO和ATS连接企业招聘流程。')}<div class="integration-grid"><article class="panel"><h3>开放 API</h3><p>用于创建招聘项目、邀请候选人和读取测评结果。</p><div class="key-box">${i.apiKey?esc(i.apiKey):'尚未生成API密钥'}</div><div class="actions">${btn(i.apiKey?'轮换密钥':'生成API密钥','api-key')}</div><small>速率限制：${i.rateLimit} 次/小时</small></article><article class="panel"><h3>Webhook</h3><p>测评完成后向企业系统主动推送结果。</p><form id="webhook-form" class="inline-form"><input name="url" type="url" placeholder="https://example.com/webhook" required><button class="btn" type="submit">添加</button></form>${i.webhooks.map(x=>`<div class="integration-row"><span>${esc(x.url)}</span>${badge(x.status)}</div>`).join('')||'<small>尚未配置Webhook</small>'}</article><article class="panel"><h3>单点登录 SSO</h3><p>支持 SAML 2.0 / OIDC 企业身份登录。</p><form id="sso-form" class="inline-form"><input name="domain" placeholder="company.com" value="${esc(i.sso.domain)}" required><button class="btn" type="submit">${i.sso.enabled?'更新':'启用'}</button></form><div>${badge(i.sso.enabled?'已启用':'未启用')}</div></article><article class="panel"><h3>ATS 招聘系统</h3><p>连接招聘系统并回传候选人测评结果。</p><form id="ats-form" class="inline-form"><select name="provider">${['Greenhouse','Workday','SAP SuccessFactors','BambooHR','自定义ATS'].map(x=>`<option ${x===i.ats.provider?'selected':''}>${x}</option>`).join('')}</select><button class="btn" type="submit">连接</button></form><div>${badge(i.ats.status)}</div></article></div></section>`,'企业集成')}

function validation(){const v=db.validation,c=v.calibration,passed=v.matrix.filter(x=>x.status==='已通过').length;shell(`<section class="page">${pageHead('测试与评分校准中心','用可追溯证据管理兼容性、评分有效性、误报率和发布门槛。',`<button class="btn" data-action="run-validation">运行本地验证</button>`)}<div class="kpis"><div class="kpi"><small>本地检查通过</small><b>${passed}/${v.matrix.length}</b><em>真实环境项目不会自动标记通过</em></div><div class="kpi"><small>基准样本</small><b>${c.sampleSize}</b><em>目标 ${c.targetSampleSize}</em></div><div class="kpi"><small>基准准确率</small><b>${c.baselineAccuracy}%</b><em>真实泰语用户样本</em></div><div class="kpi"><small>发布门槛</small><b class="date-kpi">${esc(v.releaseGate)}</b><em>${v.lastRun?new Date(v.lastRun).toLocaleString():'尚未运行'}</em></div></div><div class="grid-2"><div class="panel"><h3>测试矩阵</h3><div class="qa-list">${v.matrix.map(x=>`<article><div><b>${esc(x.area)}</b><small>${esc(x.evidence)}</small></div>${badge(x.status)}</article>`).join('')}</div></div><div><form id="calibration-form" class="panel form-stack"><h3>录入校准样本组</h3>${field('样本组名称','name')}${field('参与人数','participants','number')}${field('中位速度','medianSpeed','number')}${field('中位准确率','medianAccuracy','number')}<button class="btn" type="submit">添加校准样本</button></form><div class="panel cohort-panel"><h3>样本组</h3>${v.cohorts.map(x=>`<div class="integration-row"><span><b>${esc(x.name)}</b><br><small>${x.participants} 人 · ${x.medianSpeed} 字符/分钟 · ${x.medianAccuracy}%</small></span>${badge(x.status)}</div>`).join('')}</div></div></div></section>`,'测试与校准')}

function pilots(){const p=db.pilots,active=p.programs.filter(x=>x.status==='进行中').length;shell(`<section class="page">${pageHead('企业试点管理','以四类真实组织验证HR独立操作、候选人体验、报告价值和商业价格。',`<button class="btn" data-action="pilot-feedback">录入试点反馈</button>`)}<div class="kpis"><div class="kpi"><small>试点组织</small><b>${p.programs.length}</b><em>四类目标场景</em></div><div class="kpi"><small>进行中</small><b>${active}</b><em>封闭试点</em></div><div class="kpi"><small>目标参与者</small><b>${p.programs.reduce((n,x)=>n+x.target,0)}</b><em>候选人与HR</em></div><div class="kpi"><small>平均反馈</small><b>${p.feedback.length?(p.feedback.reduce((n,x)=>n+x.score,0)/p.feedback.length).toFixed(1):'—'}</b><em>满分5分</em></div></div><div class="table-wrap"><table><thead><tr><th>试点组织</th><th>场景</th><th>负责人</th><th>开始日期</th><th>完成/目标</th><th>成功标准</th><th>状态</th><th>操作</th></tr></thead><tbody>${p.programs.map(x=>`<tr><td><b>${esc(x.organization)}</b></td><td>${esc(x.segment)}</td><td>${esc(x.owner)}</td><td>${esc(x.startDate)}</td><td>${x.completed}/${x.target}</td><td class="wrap-cell">${esc(x.successMetric)}</td><td>${badge(x.status)}</td><td>${btn('推进状态','advance-pilot',x.id)}</td></tr>`).join('')}</tbody></table></div><div class="grid-2 pilot-bottom"><div class="panel"><h3>试点验收标准</h3><div class="settings-list">${Object.entries(p.criteria).map(([key,value])=>`<label class="setting-row"><span><b>${({hrIndependent:'HR可以独立创建测评',candidateClarity:'候选人理解测试流程',reportDecisionValue:'报告支持招聘决策',thresholdReasonable:'岗位合格线合理',pricingValidated:'企业愿意按当前价格购买',integrityAcceptable:'防作弊误报率可接受'}[key])}</b></span><input type="checkbox" ${value?'checked':''} disabled></label>`).join('')}</div></div><div class="panel"><h3>最近反馈</h3><div class="review-list">${p.feedback.map(x=>`<article><div><b>${esc(x.category)} · ${x.score}/5</b><small>${esc(x.comment)}</small></div>${badge(x.role)}</article>`).join('')}</div></div></div></section>`,'企业试点')}

function operations(){recalculateOperations();const o=db.operations,m=o.metrics,ready=o.launchChecklist.filter(x=>x.status==='已完成').length;shell(`<section class="page">${pageHead('上线与持续运营','只有生产依赖、合规和企业试点全部验收后，系统才允许标记为上线就绪。',`<button class="btn" data-action="refresh-metrics">刷新运营指标</button>`)}<div class="kpis"><div class="kpi"><small>上线状态</small><b class="date-kpi">${esc(o.launchStatus)}</b><em>${ready}/${o.launchChecklist.length} 项完成</em></div><div class="kpi"><small>邀请开始率</small><b>${m.startRate}%</b><em>已开始 / 已邀请</em></div><div class="kpi"><small>测试完成率</small><b>${m.completionRate}%</b><em>已完成 / 已开始</em></div><div class="kpi"><small>人工复核率</small><b>${m.integrityReviewRate}%</b><em>异常和监考抽查</em></div></div><div class="grid-2"><div class="panel"><h3>正式上线检查清单</h3><div class="launch-list">${o.launchChecklist.map(x=>`<article><button class="check-button ${x.status==='已完成'?'done':''}" data-action="toggle-launch" data-id="${x.id}">${x.status==='已完成'?'✓':'○'}</button><div><b>${esc(x.item)}</b><small>${esc(x.owner)}</small></div>${badge(x.status)}</article>`).join('')}</div><p class="muted">本地勾选仅用于项目跟踪，不代表生产服务已自动通过验证。</p></div><div class="panel"><h3>持续优化队列</h3><div class="improvement-list">${o.improvements.map(x=>`<article><span class="priority ${x.priority}">${esc(x.priority)}</span><div><b>${esc(x.title)}</b><small>${esc(x.source)}</small></div>${badge(x.status)}${btn('推进','advance-improvement',x.id)}</article>`).join('')}</div><button class="btn secondary" data-action="new-improvement">添加优化任务</button></div></div></section>`,'上线与运营')}

function recalculateOperations(){const invited=db.candidates.filter(x=>x.invitedAt).length,started=db.candidates.filter(x=>['已开始','已完成'].includes(x.status)).length,completed=db.candidates.filter(x=>x.status==='已完成').length,reviewed=db.reviewQueue.length;db.operations.metrics={...db.operations.metrics,inviteRate:db.candidates.length?Math.round(invited/db.candidates.length*100):0,startRate:invited?Math.round(started/invited*100):0,completionRate:started?Math.round(completed/started*100):0,dropOffRate:started?Math.round((started-completed)/started*100):0,integrityReviewRate:completed?Math.round(reviewed/completed*100):0,avgScore:db.results.length?Math.round(db.results.reduce((n,x)=>n+x.score,0)/db.results.length):0}}

function members(){shell(`<section class="page">${pageHead('团队与权限','企业数据按组织隔离，关键操作进入审计记录。',canEdit()?`<button class="btn" data-action="new-member">邀请成员</button>`:'')}<div class="table-wrap"><table><thead><tr><th>成员</th><th>邮箱</th><th>角色</th><th>权限范围</th><th>状态</th></tr></thead><tbody>${db.members.map(m=>`<tr><td><b>${esc(m.name)}</b></td><td>${esc(m.email)}</td><td>${esc(m.role)}</td><td>${m.role==='企业管理员'?'全部权限':m.role==='招聘经理'?'项目与候选人管理':m.role==='面试官'?'查看结果与备注':'只读查看'}</td><td>${badge(m.status)}</td></tr>`).join('')}</tbody></table></div></section>`,'企业团队')}

function settings(){shell(`<section class="page">${pageHead('企业设置','管理品牌、数据保留规则和本地演示数据。')}<div class="grid-2"><div class="panel"><h3>组织资料</h3><p><b>${esc(db.organization.name)}</b></p><p>国家 / 地区：${esc(db.organization.country)}</p><p>套餐：${esc(db.organization.plan)}</p><p>数据保留：${db.organization.dataRetentionDays} 天</p></div><div class="panel"><h3>演示环境</h3><p>当前版本使用浏览器本地数据，用于功能验收。正式上线需接入生产认证、数据库和邮件服务。</p><button class="btn danger" data-action="reset">重置演示数据</button></div></div></section>`,'企业设置')}

function reportView(id){const r=result(id),c=candidate(r?.candidateId),p=project(r?.projectId),t=template(p?.templateId);if(!r)return results();selectedReport=id;shell(`<section class="page">${pageHead('候选人测评报告','报告编号 '+esc(r.id),`<div class="actions no-print"><button class="btn secondary" data-view="results">返回结果</button><button class="btn" data-action="print">打印 / 保存PDF</button></div>`)}<article class="report"><div class="report-head"><div><h2>ThaiType Business</h2><div>企业泰语输入能力测评报告</div><p>${esc(db.organization.name)} · ${esc(p?.name)}</p></div><div><div class="report-score">${r.score}</div><small>综合评分 / 100</small></div></div><div class="report-grid"><div><small>有效速度</small><b>${r.speed}</b>字符/分钟</div><div><small>最终准确率</small><b>${r.accuracy}%</b></div><div><small>首次准确率</small><b>${r.firstAccuracy}%</b></div><div><small>稳定性</small><b>${r.stability}</b></div></div><div class="decision"><h3>${esc(r.recommendation)}</h3><p>${r.accuracy>=t.minAccuracy?'准确率达到岗位要求。':'准确率低于岗位要求。'} ${r.speed>=t.minSpeed?'输入速度达到岗位要求。':'输入速度仍需提升。'} 结果可信度：${esc(r.integrityLabel)}。</p></div><div class="grid-2" style="margin-top:22px"><div><h3>候选人与岗位</h3><p>候选人：<b>${esc(c?.name)}</b></p><p>测评岗位：${esc(t?.name)}</p><p>完成时间：${new Date(r.completedAt).toLocaleString()}</p></div><div><h3>输入质量</h3><p>错误 ${r.errors.wrong} · 漏字 ${r.errors.missing} · 多字 ${r.errors.extra} · 修改 ${r.errors.corrections}</p><p>完成率 ${r.completion}% · 可信度评分 ${r.integrity}</p><p>异常记录：${r.anomalies.length?r.anomalies.map(x=>esc(x.type)).join('、'):'未发现显著异常'}</p></div></div></article></section>`,'测评报告')}

function modal(title,body){const el=document.querySelector('#modal');el.hidden=false;el.innerHTML=`<div class="dialog"><div class="dialog-head"><h2>${title}</h2><button class="close" data-action="close">×</button></div>${body}</div>`;localize(el);el.querySelector('.close').onclick=()=>el.hidden=true;bindForms()}
const field=(label,name,type='text',value='',wide='')=>`<label class="${wide}">${label}<input name="${name}" type="${type}" value="${esc(value)}" required></label>`

function projectForm(){modal('创建招聘项目',`<form id="project-form" class="form-grid">${field('项目名称','name')}${field('负责人','owner','text',db.currentUser.name)}<label>岗位模板<select name="templateId">${db.templates.filter(x=>x.status==='启用').map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label>${field('截止日期','deadline','date')}<div class="wide actions"><button class="btn" type="submit">创建项目</button></div></form>`)}
function candidateForm(projectId=''){modal('添加候选人',`<form id="candidate-form" class="form-grid">${field('候选人姓名','name')}${field('邮箱','email','email')}<label class="wide">招聘项目<select name="projectId">${db.projects.map(x=>`<option value="${x.id}" ${x.id===projectId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>${field('标签（逗号分隔）','tags','text','','wide')}<label class="wide">内部备注<textarea name="notes" rows="3"></textarea></label><div class="wide actions"><button class="btn" type="submit">添加并生成邀请链接</button></div></form>`)}
function templateForm(existing){const t=existing||{name:'',description:'',duration:5,minSpeed:30,minAccuracy:95,weights:{speed:30,accuracy:45,stability:15,integrity:10},questionIds:[]};modal(existing?'编辑岗位模板':'自定义岗位模板',`<form id="template-form" data-id="${t.id||''}" class="form-grid">${field('模板名称','name','text',t.name)}${field('测试时长（分钟）','duration','number',t.duration)}${field('最低速度（字符/分钟）','minSpeed','number',t.minSpeed)}${field('最低准确率（%）','minAccuracy','number',t.minAccuracy)}${field('岗位说明','description','text',t.description,'wide')}<div class="wide"><b>评分权重（总计100）</b><div class="weight-row">${Object.entries(t.weights).map(([k,v])=>field({speed:'速度',accuracy:'准确率',stability:'稳定性',integrity:'可信度'}[k],k,'number',v)).join('')}</div></div><label class="wide">测评题目<select name="questionIds" multiple size="5">${db.questions.map(q=>`<option value="${q.id}" ${t.questionIds.includes(q.id)?'selected':''}>${esc(q.title)} · ${esc(q.type)}</option>`).join('')}</select></label><div class="wide actions"><button class="btn" type="submit">保存模板版本</button></div></form>`)}
function questionForm(){modal('添加题目',`<form id="question-form" class="form-grid">${field('题目名称','title')}<label>题型<select name="type">${['标准抄写','业务场景','结构化录入','泰语听打','长文稳定性'].map(x=>`<option>${x}</option>`).join('')}</select></label>${field('行业','industry') }<label>难度<select name="difficulty"><option>简单</option><option selected>中等</option><option>困难</option></select></label><label class="wide">泰语内容<textarea name="text" lang="th" rows="5" required></textarea></label><div class="wide actions"><button class="btn" type="submit">保存题目</button></div></form>`)}
function statusForm(c){modal('更新候选人状态',`<form id="status-form" data-id="${c.id}" class="form-grid"><label class="wide">状态<select name="status">${['待邀请','已邀请','已开始','已完成','需复测','进入下一轮','淘汰','已录用'].map(x=>`<option value="${x}" ${x===c.status?'selected':''}>${x}</option>`).join('')}</select></label><div class="wide actions"><button class="btn" type="submit">保存状态</button></div></form>`)}

function bindGlobal(){
  document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>{view=x.dataset.view;render()})
  document.querySelector('#role-switch').onchange=e=>{db.currentUser.role=e.target.value;stamp(db,`切换演示角色为 ${e.target.value}`);render()}
  document.querySelectorAll('[data-action]').forEach(x=>x.onclick=()=>action(x.dataset.action,x.dataset.id))
  document.querySelector('#candidate-search')?.addEventListener('input',filterCandidates);document.querySelector('#candidate-status')?.addEventListener('change',filterCandidates)
  bindForms()
}
function filterCandidates(){const q=document.querySelector('#candidate-search').value.toLowerCase(),s=document.querySelector('#candidate-status').value;document.querySelector('#candidate-rows').innerHTML=candidateRows(db.candidates.filter(x=>(x.name+x.email).toLowerCase().includes(q)&&(!s||x.status===s)))}
function action(name,id){
  if(name==='new-project')projectForm();if(name==='new-candidate')candidateForm(id);if(name==='new-template')templateForm();if(name==='edit-template')templateForm(template(id));if(name==='new-question')questionForm();if(name==='close')document.querySelector('#modal').hidden=true
  if(name==='clone-template'){const t=structuredClone(template(id));t.id=makeId('tpl');t.name+='（副本）';t.version=1;db.templates.push(t);stamp(db,`复制岗位模板：${t.name}`);render()}
  if(name==='copy-link'){navigator.clipboard.writeText(inviteUrl(candidate(id).token));alert(tr('专属测评链接已复制'))}
  if(name==='report')reportView(id);if(name==='print')window.print()
  if(name==='status')statusForm(candidate(id))
  if(name==='export'){const rows=[['候选人','项目','综合分','有效速度','准确率','可信度','招聘建议'],...db.results.map(r=>{const c=candidate(r.candidateId);return[c?.name,project(r.projectId)?.name,r.score,r.speed,r.accuracy,r.integrityLabel,r.recommendation]})];const blob=new Blob(['\ufeff'+csv(rows)],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ThaiType招聘测评结果.csv';a.click();URL.revokeObjectURL(a.href)}
  if(name==='reset'&&confirm(tr('确定重置所有本地演示数据吗？'))){db=reset();view='dashboard';render()}
  if(name==='privacy-request')modal('新建隐私请求',`<form id="privacy-form" class="form-grid">${field('候选人姓名','candidate')}<label>请求类型<select name="type"><option>数据导出</option><option>删除数据</option></select></label><div class="wide actions"><button class="btn" type="submit">提交请求</button></div></form>`)
  if(name==='buy-package'){const pkg=db.billing.packages.find(x=>x.id===id);if(confirm(`${tr('确认模拟购买')} ${tr(pkg.name)}?`)){db.organization.credits+=pkg.credits;db.billing.transactions.unshift({id:makeId('txn'),type:pkg.name,credits:pkg.credits,amount:pkg.price,status:'已入账',createdAt:new Date().toISOString()});stamp(db,`购买额度包：${pkg.name}`);render()}}
  if(name==='toggle-notification'){const item=db.notifications.templates.find(x=>x.id===id);item.enabled=!item.enabled;stamp(db,`${item.enabled?'启用':'停用'}通知：${item.type}`);render()}
  if(name==='send-test'){db.notifications.logs.unshift({id:makeId('nl'),type:'测试通知',recipient:db.currentUser.email,status:'模拟送达',createdAt:new Date().toISOString()});stamp(db,'发送测试通知');render()}
  if(name==='api-key'){db.integrations.apiEnabled=true;db.integrations.apiKey=`tt_live_${crypto.randomUUID().replaceAll('-','').slice(0,24)}`;stamp(db,'生成或轮换API密钥');render()}
  if(name==='run-validation'){for(const item of db.validation.matrix)if(['五语言界面','断网恢复','权限与数据隔离','报告与导出'].includes(item.area))item.status='已通过';db.validation.lastRun=new Date().toISOString();db.validation.releaseGate=db.validation.matrix.every(x=>x.status==='已通过')?'待人工发布批准':'未通过';stamp(db,'运行本地发布验证');render()}
  if(name==='pilot-feedback')modal('录入试点反馈',`<form id="pilot-feedback-form" class="form-grid"><label class="wide">试点项目<select name="pilotId">${db.pilots.programs.map(x=>`<option value="${x.id}">${esc(x.organization)}</option>`).join('')}</select></label><label>反馈角色<select name="role"><option>HR</option><option>候选人</option><option>用人经理</option><option>管理员</option></select></label><label>评分（1-5）<input name="score" type="number" min="1" max="5" value="5" required></label>${field('反馈类别','category') }<label class="wide">具体反馈<textarea name="comment" rows="3" required></textarea></label><div class="wide actions"><button class="btn" type="submit">保存反馈</button></div></form>`)
  if(name==='advance-pilot'){const item=db.pilots.programs.find(x=>x.id===id),states=['待邀请','准备中','进行中','已完成','已验收'],index=states.indexOf(item.status);item.status=states[Math.min(states.length-1,index+1)];stamp(db,`推进企业试点：${item.organization} → ${item.status}`);render()}
  if(name==='refresh-metrics'){recalculateOperations();stamp(db,'刷新运营指标');render()}
  if(name==='toggle-launch'){const item=db.operations.launchChecklist.find(x=>x.id===id);item.status=item.status==='已完成'?'待完成':'已完成';const all=db.operations.launchChecklist.every(x=>x.status==='已完成');db.operations.launchStatus=all?'待最终人工复核':'未就绪';stamp(db,`更新上线检查：${item.item}`);render()}
  if(name==='advance-improvement'){const item=db.operations.improvements.find(x=>x.id===id),states=['待处理','进行中','已完成'],index=states.indexOf(item.status);item.status=states[Math.min(states.length-1,index+1)];stamp(db,`推进优化任务：${item.title}`);render()}
  if(name==='new-improvement')modal('添加优化任务',`<form id="improvement-form" class="form-grid">${field('任务名称','title')}<label>来源<select name="source"><option>评分校准</option><option>企业试点</option><option>持续运营</option><option>客户反馈</option></select></label><label>优先级<select name="priority"><option>高</option><option>中</option><option>低</option></select></label><div class="wide actions"><button class="btn" type="submit">添加任务</button></div></form>`)
}
function bindForms(){
  document.querySelector('#project-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));db.projects.push({...f,id:makeId('p'),status:'进行中',createdAt:new Date().toISOString()});stamp(db,`创建招聘项目：${f.name}`);view='projects';render()})
  document.querySelector('#candidate-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),token=crypto.randomUUID().slice(0,8).toUpperCase();db.candidates.push({...f,id:makeId('c'),token,status:'已邀请',invitedAt:new Date().toISOString(),resultId:null,tags:f.tags.split(',').filter(Boolean)});stamp(db,`添加候选人：${f.name}`);view='candidates';render()})
  document.querySelector('#template-form')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd),weights={speed:+f.speed,accuracy:+f.accuracy,stability:+f.stability,integrity:+f.integrity};if(Object.values(weights).reduce((a,b)=>a+b,0)!==100)return alert(tr('评分权重合计必须为100'));const old=template(e.target.dataset.id),data={id:old?.id||makeId('tpl'),name:f.name,description:f.description,duration:+f.duration,minSpeed:+f.minSpeed,minAccuracy:+f.minAccuracy,weights,questionIds:fd.getAll('questionIds'),status:'启用',version:(old?.version||0)+1};if(old)Object.assign(old,data);else db.templates.push(data);stamp(db,`保存岗位模板：${data.name} V${data.version}`);view='templates';render()})
  document.querySelector('#question-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));db.questions.push({...f,id:makeId('q'),status:'启用'});stamp(db,`添加题目：${f.title}`);view='questions';render()})
  document.querySelector('#status-form')?.addEventListener('submit',e=>{e.preventDefault();const c=candidate(e.target.dataset.id),next=new FormData(e.target).get('status');c.status=next;stamp(db,`更新 ${c.name} 状态为 ${next}`);view='candidates';render()})
  document.querySelector('#proctoring-form')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);for(const key of ['enabled','photo','cameraSnapshots','facePresence','multipleFaces','idVerification','microphone','screenRecording','alternativeAllowed'])db.proctoring[key]=fd.has(key);db.proctoring.snapshotInterval=+fd.get('snapshotInterval');db.proctoring.retentionDays=+fd.get('retentionDays');stamp(db,'更新高级监考策略');render()})
  document.querySelector('#privacy-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));db.privacy.requests.unshift({id:makeId('privacy'),...f,status:'待处理',createdAt:new Date().toISOString()});stamp(db,`创建隐私请求：${f.type}`);view='compliance';render()})
  document.querySelector('#webhook-form')?.addEventListener('submit',e=>{e.preventDefault();const url=new FormData(e.target).get('url');db.integrations.webhooks.push({id:makeId('wh'),url,status:'待验证'});stamp(db,'添加Webhook');render()})
  document.querySelector('#sso-form')?.addEventListener('submit',e=>{e.preventDefault();db.integrations.sso={enabled:true,provider:'SAML 2.0',domain:new FormData(e.target).get('domain')};stamp(db,'启用企业单点登录');render()})
  document.querySelector('#ats-form')?.addEventListener('submit',e=>{e.preventDefault();db.integrations.ats={provider:new FormData(e.target).get('provider'),status:'模拟连接',lastSync:new Date().toISOString()};stamp(db,'连接ATS招聘系统');render()})
  document.querySelector('#calibration-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),cohort={id:makeId('cohort'),name:f.name,participants:+f.participants,medianSpeed:+f.medianSpeed,medianAccuracy:+f.medianAccuracy,status:+f.participants>=30?'可用于校准':'样本不足'};db.validation.cohorts.push(cohort);const total=db.validation.cohorts.reduce((n,x)=>n+x.participants,0);db.validation.calibration.sampleSize=total;db.validation.calibration.baselineSpeed=Math.round(db.validation.cohorts.reduce((n,x)=>n+x.medianSpeed*x.participants,0)/total);db.validation.calibration.baselineAccuracy=+(db.validation.cohorts.reduce((n,x)=>n+x.medianAccuracy*x.participants,0)/total).toFixed(1);db.validation.calibration.lastUpdated=new Date().toISOString();const scoreItem=db.validation.matrix.find(x=>x.id==='qa_scoring');if(total>=db.validation.calibration.targetSampleSize)scoreItem.status='待专家复核';stamp(db,`添加校准样本：${f.name}`);view='validation';render()})
  document.querySelector('#pilot-feedback-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));db.pilots.feedback.unshift({id:makeId('fb'),...f,score:+f.score,createdAt:new Date().toISOString()});stamp(db,'录入企业试点反馈');view='pilots';render()})
  document.querySelector('#improvement-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));db.operations.improvements.unshift({id:makeId('imp'),...f,status:'待处理'});stamp(db,`添加优化任务：${f.title}`);view='operations';render()})
}
function render(){({dashboard,projects,candidates,templates:templatesView,questions:questionsView,results,proctoring,compliance,billing,notifications,integrations,validation,pilots,operations,members,settings}[view]||dashboard)()}
render()
